{
 "title": "FSlibre-data",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1d",
 "panels": [
  {
   "title": "TiR",
   "type": "grafana-piechart-panel",
   "description": "Time in range",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "alias": "low",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "glucose",
     "query": "SELECT count(\"value_mgdl\") FROM \"glucose\" WHERE (\"value_mgdl\" < 70) and  $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value_mgdl" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "value_mgdl", "operator": "<", "value": "70" }
     ]
    },
    {
     "alias": "good",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "glucose",
     "query": "SELECT count(\"value_mgdl\") FROM \"glucose\" WHERE (\"value_mgdl\" > 70 AND \"value_mgdl\" < 180) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value_mgdl" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "value_mgdl", "operator": ">", "value": "70" },
      { "condition": "AND", "key": "value_mgdl", "operator": "<", "value": "180" }
     ]
    },
    {
     "alias": "high",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "glucose",
     "query": "SELECT count(\"value_mgdl\") FROM \"glucose\" WHERE (\"value_mgdl\" > 180) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value_mgdl" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "value_mgdl", "operator": ">", "value": "180" }
     ]
    }
   ]
  },
  {
   "title": "AVG",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "glucose",
     "query": "SELECT mean(\"value_mgdl\") FROM \"glucose\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value_mgdl" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AVG/StDev",
   "type": "snuids-trafficlights-panel",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 0 },
   "targets": [
    {
     "alias": "Avg/StDev",
     "query": "SELECT mean(\"value_mgdl\") / stddev(\"value_mgdl\") FROM \"glucose\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "StDev",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "glucose",
     "query": "SELECT stddev(\"value_mgdl\") FROM \"glucose\" WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value_mgdl" ], "type": "field" },
       {
        "params": [],
        "type": "stddev"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HbA1c",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "glucose",
     "query": "SELECT ((2.59 + mean(\"value_mmol\"))  / 1.59) FROM \"glucose\" WHERE time <= now() and time >= now() -90d  group by time($interval)",
     "select": [
      [
       { "params": [ "value_mmol" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1.59" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Glucose",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "conmgdL" }
   ],
   "targets": [
    {
     "alias": "mg/dl",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "glucose",
     "query": "SELECT mean(\"value_mgdl\") FROM \"glucose\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value_mgdl" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Delta",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "conmgdL" }
   ],
   "targets": [
    {
     "alias": "Δ mg/dl",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "glucose",
     "query": "SELECT derivative(mean(\"value_mgdl\"), 5m) FROM \"glucose\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value_mmol" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Histogram",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Count" } },
   "yaxes": [
    { "format": "Count" }
   ],
   "targets": [
    {
     "alias": "glucose",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "glucose",
     "select": [
      [
       { "params": [ "value_mgdl" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}